services:
  delivery:
    depends_on:
      - converter
    build:
      context: .
      dockerfile: ./src/delivery/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - videos-vol:/videos

  converter:
    depends_on:
      - broker
    build:
      context: .
      dockerfile: ./src/converter/Dockerfile
    volumes:
      - videos-vol:/videos

  broker:
    image: redis

volumes:
  videos-vol:
